#%RAML 1.0 Library
usage:
traits:
 transactionId: !include header-transactionId-trait.raml
 departureLocationCodes: !include queryParams-departureLocationCode-traits.raml
 destinationLocationcode: !include queryParams-destinationLocationCode-trait.raml